/**
 * First-run account provisioning.
 *
 * There is no self-registration and no default account (PRD §6, §33, §34), so
 * the very first Admin has to be created out of band. An operator runs
 * `provisionFirstAdmin` once from the Apps Script editor.
 *
 * Nothing here is reachable through the web app — these functions are not in
 * the action table.
 *
 * Procedure (also in google-apps-script/README.md):
 *
 *   1. Set SESSION_HMAC_SECRET, PASSWORD_PEPPER and TRACKING_SPREADSHEET_ID
 *      in Script Properties.
 *   2. Add two more, temporarily: BOOTSTRAP_ADMIN_EMAIL and
 *      BOOTSTRAP_ADMIN_PASSWORD.
 *   3. Run `runProvisioning` once from the editor and read the log.
 *      Both bootstrap properties are deleted automatically.
 *   4. Deliver the password to the person out of band. Never email it
 *      alongside the application URL.
 *
 * The password never travels over HTTP because the endpoint is public: an
 * unauthenticated "create the first admin" action would be a takeover
 * primitive for whoever called it first.
 */

import { requireProperty } from '../config/properties';
import { writeAudit } from '../audit/audit-log';
import { createPasswordRecord } from './password';
import * as users from '../sheets/users-repository';

export interface ProvisionResult {
  created: boolean;
  message: string;
}

/**
 * Create the first Admin.
 *
 * Refuses to run when any account already exists, so it cannot be used to
 * quietly add a second Admin later — that goes through `admin.createUser`.
 */
export function provisionFirstAdmin(email: string, password: string): ProvisionResult {
  if (!users.isEmpty()) {
    return {
      created: false,
      message: 'Accounts already exist. Use the admin.createUser action instead.',
    };
  }

  if (password.length < 12) {
    return { created: false, message: 'Choose a password of at least 12 characters.' };
  }

  const material = createPasswordRecord(password, requireProperty('PASSWORD_PEPPER'));
  const normalised = users.normaliseEmail(email);

  users.createUser({
    email: normalised,
    passwordHash: material.hash,
    salt: material.salt,
    iterations: material.iterations,
    role: 'Admin',
  });

  writeAudit({
    actor: 'system',
    action: 'auth.provisionFirstAdmin',
    target: normalised,
    outcome: 'success',
    requestId: 'provisioning',
  });

  return { created: true, message: `Admin account created for ${normalised}.` };
}

/** Temporary Script Properties, read once and deleted immediately after use. */
export const BOOTSTRAP_EMAIL_PROPERTY = 'BOOTSTRAP_ADMIN_EMAIL';
export const BOOTSTRAP_PASSWORD_PROPERTY = 'BOOTSTRAP_ADMIN_PASSWORD';

/**
 * Operator entry point. Run once from the Apps Script editor.
 *
 * The credentials come from two temporary Script Properties rather than from
 * constants in this file, for three reasons:
 *
 *   1. `Code.js` is generated by esbuild. Editing it in the online editor puts
 *      a password into an artefact that the next `clasp push` overwrites — easy
 *      to leave behind, easy to lose.
 *   2. A password typed into source risks being committed.
 *   3. The editor's Run button only calls zero-argument functions, so reading
 *      the values from configuration is the only ergonomic option.
 *
 * Both properties are DELETED as soon as they are read, whether or not the
 * account was created, so the password does not linger in project settings.
 */
export function runProvisioning(): void {
  const store = PropertiesService.getScriptProperties();

  const email = store.getProperty(BOOTSTRAP_EMAIL_PROPERTY) ?? '';
  const password = store.getProperty(BOOTSTRAP_PASSWORD_PROPERTY) ?? '';

  // Clear first, so an exception below cannot leave the password in place.
  store.deleteProperty(BOOTSTRAP_EMAIL_PROPERTY);
  store.deleteProperty(BOOTSTRAP_PASSWORD_PROPERTY);

  if (email.length === 0 || password.length === 0) {
    console.log(
      `Set Script Properties ${BOOTSTRAP_EMAIL_PROPERTY} and ${BOOTSTRAP_PASSWORD_PROPERTY}, then run this again. ` +
        'Both are deleted automatically once read.',
    );
    return;
  }

  console.log(provisionFirstAdmin(email, password).message);
  console.log('The bootstrap properties have been deleted. Sign in and change nothing else here.');
}
