/**
 * Saving a quotation's documents to the Drive archive.
 *
 * ---------------------------------------------------------------------------
 * THE BROWSER NEVER TOUCHES DRIVE
 * ---------------------------------------------------------------------------
 * There is no Drive SDK here, no `googleapis`, no `gapi`, and no Google
 * credential of any kind. This module posts base64 to the existing Apps Script
 * endpoint, and Apps Script — running as the deploying account, inside the
 * authorization the deployment was granted — does the filing.
 *
 * That is not merely convenient: a browser holding a Drive credential could
 * write anywhere in the company's Drive, and the archive's structure would stop
 * being something the server can guarantee.
 *
 * Files travel as base64 in the same `text/plain` POST as every other action
 * (§15.2). A multipart body or an extra header would trigger a CORS preflight
 * that Apps Script cannot answer, and the request would simply fail.
 */

import { callAction } from '@/services/api/client';
import { parseDriveTarget, type DriveTarget } from '@shared/drive-links';
import { DOCUMENT_KINDS, type DocumentKind } from '@shared/drive-paths';
import { bytesToBase64 } from '@/utils/base64';

/** What to send. A retry may carry only the documents that are missing. */
export type DocumentPayload = Partial<Record<DocumentKind, string>>;

export interface SaveToDriveInput {
  /** The key to everything: it resolves to the issued number and the folder. */
  draftId: string;
  documents: DocumentPayload;
}

export interface SaveToDriveResult {
  /** `partial` means some files uploaded and some did not. Handle both. */
  outcome: 'success' | 'partial';
  draftId: string;
  quotationNumber: string;
  folder: DriveTarget;
  /** `['2026', 'August', 'SFC-RUH-QTN-2026-004']`. */
  path: string[];
  pathLabel: string;
  files: { pdf: DriveTarget | null; docx: DriveTarget | null };
  /** Empty on success; what a Retry Upload must send. */
  missing: DocumentKind[];
}

interface RawResult {
  outcome?: unknown;
  draftId?: unknown;
  quotationNumber?: unknown;
  folder?: unknown;
  path?: unknown;
  pathLabel?: unknown;
  files?: { pdf?: unknown; docx?: unknown };
  missing?: unknown;
}

function optionalTarget(value: unknown): DriveTarget | null {
  return value === null || value === undefined ? null : parseDriveTarget(value);
}

/**
 * Re-brand the response.
 *
 * Every URL is validated on the way in, so a malformed link fails here rather
 * than becoming a dead "Open folder" button (PRD §34).
 */
function parseResult(raw: RawResult): SaveToDriveResult {
  const missing = Array.isArray(raw.missing)
    ? raw.missing.filter((kind): kind is DocumentKind =>
        (DOCUMENT_KINDS as readonly string[]).includes(kind as string),
      )
    : [];

  return {
    outcome: raw.outcome === 'partial' ? 'partial' : 'success',
    draftId: typeof raw.draftId === 'string' ? raw.draftId : '',
    quotationNumber: typeof raw.quotationNumber === 'string' ? raw.quotationNumber : '',
    folder: parseDriveTarget(raw.folder),
    path: Array.isArray(raw.path) ? raw.path.filter((s): s is string => typeof s === 'string') : [],
    pathLabel: typeof raw.pathLabel === 'string' ? raw.pathLabel : '',
    files: {
      pdf: optionalTarget(raw.files?.pdf),
      docx: optionalTarget(raw.files?.docx),
    },
    missing,
  };
}

export async function saveToDrive(
  input: SaveToDriveInput,
  token: string,
): Promise<SaveToDriveResult> {
  const raw = await callAction<SaveToDriveInput, RawResult>('quotation.uploadToDrive', input, {
    token,
    // A megabyte or two of base64 over a slow connection, then Drive's own
    // round trips. The default 60 s is not enough for a large quotation.
    timeoutMs: 180_000,
  });

  return parseResult(raw);
}

/** Encode generated bytes for the request body. */
export function encodeDocument(bytes: Uint8Array): string {
  return bytesToBase64(bytes);
}
